config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints DomainGenerator::SubdomainPresent do
    root to: 'directories#index'
    get 'account', to: 'accounts#show', as: :account
    get 'account/settings', to: 'accounts#settings', as: :account_settings
    patch 'account', to: 'accounts#update', as: :update_account
    delete 'account', to: 'accounts#destroy', as: :destroy_account

    resources :directories, only: [:show, :create, :update, :destroy]
    resources :records, only: [:create, :update, :destroy]
  end

  constraints DomainGenerator::SubdomainAbsent do
    root to: 'accounts#index'
    resources :accounts, only: [:create]
    resources :directories, only: [:index]
  end

end

app/models/directory.rb
class Directory < ApplicationRecord
  belongs_to :user, required: false

  belongs_to :parent, class_name: 'Directory', foreign_key: :directory_id, inverse_of: :children, required: false
  has_many :children, class_name: 'Directory', foreign_key: :directory_id, inverse_of: :parent, dependent: :destroy

  has_many :records, dependent: :destroy

  scope :user, ->(user_id) { where(user_id: user_id) }

  before_validation :search_for_owner

  validates_presence_of :name

  validate :singularity_of_root

  def tree
    ActiveRecord::Base.transaction { recurse }
  end

  def recurse
    tree_node.tap do |node|
      unless children.empty?
        children.each do |child|
          node['children'] << child.recurse
        end
      end
    end
  end

  private

  def tree_node
    attributes.merge('records' => records_attributes, 'children' => [])
  end

  def records_attributes
    records.inject([]) do |array, record|
      array << record.attributes.merge(record_url: record.path_to_file)
    end
  end

  # ##############
  # # Validation #
  # ##############

  def singularity_of_root
    if user
      self.errors.add(:singularity_of_root, 'Already has a root directory') if user.directories.count > 1 && directory_id.nil?
    else
      self.errors.add(:singularity_of_root, 'Already has a root directory') if Directory.count > 1 && directory_id.nil?
    end
  end

  # #########
  # # Hooks #
  # #########

  # %%TODO%% Currently sets owned based on parent folder struture.
  # This will change if users take ownership of account directories.
  def search_for_owner
    unless directory_id.nil?
      current_directory = self
      until current_directory.directory_id.nil?
        current_directory = current_directory.parent
        break if current_directory.user.present?
      end
      self.user = current_directory.user
    end
  end

end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_root_directory, only: [:index]
  before_action :find_directory, only: [:show, :update, :destroy]

  # TODO: Rethink User/Account idea
  def index
    @directory = Directory.new
  end

  def create
    directory = Directory.create(directory_params)
    respond_to do |format|
      format.js do
        render 'directory', locals: { directory: directory }
      end
    end
  end

  def show
    respond_to do |format|
      format.js do
        render 'directory'
      end
    end
  end

  def update

  end

  def destroy
    @directory.destroy
    render json: { success: true }
  end

  private

  def directory_params
    params.require(:directory).permit(:directory_id)
  end

  def find_root_directory
    @root = current_account ? params[:id] ? Directory.find(params[:id]) : Directory.find_by(directory_id: nil) : current_user.root
  end

  def find_directory
    @directory = Directory.find(params[:id])
  end

end

app/views/directories/_directory.haml
= link_to directory_path(subdomain: current_account.subdomain, id: directory.id), remote: true, class: 'directory-link' do
  .directory.relative{ id: "dir_#{directory.id}", data: { id: directory.id, name: directory.name, parent_id: directory.parent.id } }
    %i.fa.fa-folder-o.fa-5x.light
    %p= directory.name

app/views/directories/_parent_directory.haml
#currentDirectory{ data: { id: directory.id, name: directory.name } }
  - directory.children.each do |child|
    = render partial: 'directories/directory', locals: { directory: child }
.records
  - directory.records.each do |record|
    = render partial: 'records/record', locals: { record: record }

- if directory.parent.present?
  = link_to '', directory_path(subdomain: current_account.subdomain, id: directory.parent.id), remote: true, class: 'parent-link'

= form_for @directory, method: :post do |f|
  = f.text_field :name
  = f.submit 'Create'

app/views/directories/_terminal.haml
= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Ubuntu+Mono'

.terminal{ data: { account: current_account ? current_account.subdomain : nil, user: current_user ? current_user.email : nil } }
  .inline-block.miniterm
    %input{ type: 'text', id: 'terminalInput', autofocus: true }
    .line.active{ data: { line: 1, account: current_account ? current_account.subdomain : '', user: current_user ? current_user.email : nil } }
      %span#timestamp.timestamp
      - if current_account
        %span#account #{current_account.subdomain}:
      - if current_user
        %span#user= current_user.email
      %span#directory
      %span#dollar.dollar $
      %span.textOutput
      .cursor#cursor
        %span.visible _
      %span.termOutput

app/views/directories/directory.js.haml
$('.directories').empty();
$('.directories').append("#{escape_javascript( render partial: 'parent_directory', locals: { directory: @directory } )}").hide().fadeIn(1000);

app/views/directories/index.html.haml
.folders{ data: { id: @root.id } }
  .row
    .col.l12.m12.s12
      .directories
        = render partial: 'parent_directory', locals: { directory: @root }

= javascript_include_tag 'directories'