config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  constraints DomainGenerator::SubdomainPresent do
    root to: 'directories#index'
    get 'account', to: 'accounts#show', as: :account
    get 'account/settings', to: 'accounts#settings', as: :account_settings
    patch 'account', to: 'accounts#update', as: :update_account
    delete 'account', to: 'accounts#destroy', as: :destroy_account

    resources :directories, only: [:show, :create, :update, :destroy]
    resources :records, only: [:create, :update, :destroy]
  end

  constraints DomainGenerator::SubdomainAbsent do
    root to: 'accounts#index'
    resources :accounts, only: [:create]
    resources :directories, only: [:index]
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title blockadespace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.bg-teal
    - if current_user
      %ul#slide-out.side-nav
        %li
          .userView
            .background
              %img
            = link_to root_url(subdomain: 'app') do
              %span.name Home
            = link_to directories_url(subdomain: 'app') do
              %span.email My Files
            %a{href: "#!name"}
              %span.name Current User: #{current_user.id}
            %a{href: "#!email"}
              %span.email= current_user.email
            = link_to destroy_user_session_path, method: :delete do
              %span.logout Log out

        %li
          %a My Accounts
        - current_user.accounts.each do |account|
          %li
            = link_to root_url(subdomain: account.subdomain) do
              %i.material-icons>
              = account.subdomain
          %li
            = link_to 'Account', account_url(subdomain: account.subdomain)
            = link_to 'Settings', account_settings_url(subdomain: account.subdomain)
        %li
          %a{href: '#', id: 'sidebar-close'}
            %span.close Close

    %ul#dropdown1.dropdown-content
      %li
        %a{:href => "#!"} one
      %li
        %a{:href => "#!"} two
      %li.divider
      %li
        %a{:href => "#!"} three
    %nav.bg-dark
      .nav-wrapper
        = link_to root_url(subdomain: 'app'), class: 'brand-logo' do
          %h1{ style: 'margin:auto;margin-top:20px;margin-left:10px;font-size:28px;' }
            = precede 'blockade' do
              %strong space
        %ul.right.hide-on-med-and-down
          %li
            %i.fa.fa-terminal.fa-2x.terminal-trigger
          %li
            - unless current_user
              = link_to new_user_session_path, method: :post do
                %span.login Log in
          %li
            %a.dropdown-button{"data-activates" => "dropdown1", :href => "#!"}
              Menu
              %i.material-icons.right

      %a.button-collapse#left{"data-activates" => "slide-out", :href => "#"}

    - if flash.any?
      - flash.each do |k, v|
        %div{ id: "alert-#{k}" }= v

    .term
      .terminal-nav.close
        = render partial: 'directories/terminal'

    .row
      .col.s10
      .col.s2
        - if current_user
          %button.right.hamburger.hamburger--arrow-r{:type => "button"}
            %span.hamburger-box
              %span.hamburger-inner

    .container
      = yield